function General() {
    return <div>
      <h2 class="header">General info</h2>
      <p class="row-content">Hertz is an electronic label which organises events. The label is a movement of neuro-electronic music. The music inspired by neuro-psychical science. The way music influences our mind and how reality has been formed through time and the existing of human consciousness are theories that influences this musical the most. The artist on this label are Dubstep, Drum & bass, Electro and Techno artist. The line-up for the events is based on the statistical calculation based on the size of the event. Based on certain formulas the investment made for the event can be made. Multiple formulas which relate to each other will determine the investment which needs to be made. The market has the biggest influence on the formulas. The event will be determined by the current demand of the market based on a balanced principle between social and cultural demand and economy potential of the market. Based on cultural developed the event will adjust the theme. Within the festival there is a concept which defines based on a neuro-physical principle which defines the reason for our behaviour. All artist our defined and we support artist that follow this concept. In this way the development of the electronic music is most effectively integrated. This principle which guides the market is the balance constant between creating demand and reacting on it. Therefor we will form the musician that don’t relate to this principle to adjust and the market and still keep their unique way the influence our world.</p>
      <p class="row-content">All music must be adjust to certain principles of interpretation for this is how the electronic scene is influenced by certain archetypes which can have influence on the development on this genre. Based on a personality model which can be related to culture we can make an interpretation of the way we should interact with society. The true essence is returning to our natural state of being and being conscious of how humankind has influence their own evolution process trough cultural standards.</p>
      <p class="row-content">Music on the event is a lot of music of personal music of the artist that are preforming life on the event. Because there is a lot of music that is never heard and of the artist that is performing this event contains something unique.</p>
      </div>;
  }

export default General;