function Label() {
    return  <div><h2>Label</h2>
    <p>CI Hertz is a label that contains multiple segments that relate to music and culture and is located in the Netherlands. The label was developed in order to develop rational principles about cultural integration within society. The label Hertz releases Dubstep, Drum & Bass, Electro and Techno. Music from the United Kingdom and the Techno scene for Germany are of the music that is being released on this label. Neuro-rhythmic elements are the of strong influence is the Dubstep music and Neuro Drum and bass music. Based on our insight on music we influence the music scene based on our preference of electronic music. Based on a scientific view of sound and a neurological concept for the concept of music we define aspect within the music scene and the production of music as a standard within culture. In relation to current aspect within society our releases are predetermined.</p>
    <p>The concept of the music that is being related is determined by current events in society and communication that takes place between artist and business associates. Based on a neurological perception of our culture we define aspect on which we try to inform our listeners and have a positive mental influences on them.</p>
    <p>The objective of the company is the stabilise cultural integration within society based on neurological principles that relate to our perception and cognitive capabilities for rational thinking. They way culture can be defined by neurology as a process within history is related to our principles.</p>
    <p>Hertz organises events and will be in interaction with the artist that are signed for events that are related to a collective amount of event that relate to the concept of the music an artist develops. The concept for your first release will be predetermined however the next concept for the releases will be proposed and developed with multiple artist. We are planning on announcing are releases starting June 21th 2021.</p>
    </div>;
  }

export default Label;